```plantuml

@startuml interpreter-default
activate Client
Client -> Context: createContext()
activate Context
Client <-- Context: return Context
deactivate Context
Client-->AbstractExpression: parseContext()
activate AbstractExpression
AbstractExpression --> NonterminalExpression: interpet(Context context)
activate NonterminalExpression
deactivate NonterminalExpression
AbstractExpression --> TerminalExpression: interpet(Context context)
activate TerminalExpression
deactivate TerminalExpression

@enduml



@enduml

```
