

@startuml use-case
left to right direction

actor Тестировщик
actor Система_сборки
actor Менеджер
actor Администратор

Тестировщик --- (Добавление агентов)
Тестировщик --- (Изменение агентов)
Тестировщик --- (Удаление агентов)

Тестировщик --- (Подготовка сценариев)
Тестировщик --- (Изменение сценариев)
Тестировщик --- (Удаление сценариев)
(Подготовка сценариев) ..> (Выбор метода тестирования): <<include>>
(Подготовка сценариев) ..> (Выбор алгоритма тестирования): <<include>>
(Подготовка сценариев) ..> (Выбор объекта тестирования): <<include>>
(Подготовка сценариев) <.. (Добавление файла данными): <<extend>>
(Добавление файла данными) <.. (Загрузка файла с сайта): <<extend>>
(Добавление файла данными) <.. (Загрузка файла c файловой системы): <<extend>>

Тестировщик --- (Просмотр истории тестирования)
Администратор --- (Просмотр истории тестирования)
Администратор --- (Добавление квоты использования)
Администратор --- (Изменение квоты)
Администратор --- (Добавление рабочих нод)
Администратор --- (Удаление рабочих нод)
Администратор --- (Просмотр рабочих нод)

Менеджер --- (Получение отчетов по тестированию)
Менеджер --- (Запуск тестов из истории тестирования)

Тестировщик --|> Система_сборки
Тестировщик --|> Менеджер

Система_сборки --- (Запуск тестирования)
Система_сборки --- (Подключение к WebHook)
(Подключение к WebHook) <.. (Получение метрик): <<extend>>
(Подключение к WebHook) <.. (Получение результата тестирования): <<extend>>

(Запуск тестирования) ..> (Выбор агентов): <<include>>
(Запуск тестирования) ..> (Выбор сценариев): <<include>>
(Запуск тестирования) <.. (Загрузка конфигурационного файла) : <<extend>>


@enduml
